### ISSUE TITLE
Subscription dosen't work

### ISSUE THREAD

**Issue by jedrus2000** [jstadnicki/isthereanynews#35] opened 2017-10-15 21:22 UTC
version 0.1.5

When clicking on Subscription it got stuck.

Dev console shows : Error: [$http:baddata] Data must be a valid JSON object. Received: "<!DOCTYPE html>

    at angular.js:116
    at defaultHttpResponseTransform (angular.js:11271)
    at angular.js:11364
    at forEach (angular.js:410)
    at transformData (angular.js:11363)
    at transformResponse (angular.js:12204)
    at processQueue (angular.js:17000)
    at angular.js:17044
    at Scope.$digest (angular.js:18182)
    at Scope.$apply (angular.js:18480) "Possibly unhandled rejection: {}"
(anonymous) @ angular.js:14642
(anonymous) @ angular.js:11102
processChecks @ angular.js:17026
$digest @ angular.js:18182
$apply @ angular.js:18480
done @ angular.js:12501
completeRequest @ angular.js:12727
requestLoaded @ angular.js:12655
XMLHttpRequest.send (async)
(anonymous) @ angular.js:12701
sendReq @ angular.js:12446
serverRequest @ angular.js:12198
processQueue @ angular.js:17000
(anonymous) @ angular.js:17044
$digest @ angular.js:18182
$apply @ angular.js:18480
bootstrapApply @ angular.js:1952
invoke @ angular.js:5040
doBootstrap @ angular.js:1950
bootstrap @ angular.js:1970
angularInit @ angular.js:1855
(anonymous) @ angular.js:33826
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2
R @ jquery-3.1.1.min.js:3
angular.js:12701 XHR finished loading: GET "http://isthereanynews.pl/Subscriptions/MyChannelList".

**Comment by jstadnicki** [comment] 2017-11-12 08:26
Tried to reproduce it on 0.1.6 (which is on production now) works for me. If you be so kind and tried again.

**Comment by jstadnicki** [comment] 2017-11-18 06:57
Fixed in version 0.1.6.1

**Closed by jstadnicki** 2017-11-18 06:57 UTC
